var age = 25;
age = true;
age = 'Hello';
age = { name: "Luigi" };
var mixed = [];
mixed.push(4);
mixed.push("Hello");
mixed.push(false);
var ninja;
ninja = { name: "Yoshi", age: 25 };
ninja = { name: false, age: '25' };
